# fly.toml app configuration file generated for salable-seats on 2024-04-16T16:27:08+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "salable-seats"
primary_region = "lhr"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0


[env]
  TEST = 'HELLO'